# CONTIENT LES CONFIGURATIOND DE TOUS LES SERVICES A PARTAGER, IL SERA LANCER EN PREMIER POUR QUE LES AUTRES PUISSENT CHERCHER LEUR CONFIGURATION
# CE SONT LES CONFIGURATIONS POUR CHAQUE REQUETTES QU'ON VERA DANS LE PROJET
# http://localhost:8080/application/health : PERMET DE DEMANDER LA CONFIG DU SERVEUR
project = banking-project
class = Master pro 2025-2026
semester = 2
prof = Mr. Dupont
student = Komol Daniel
heure = 16h par semaine
