# CONTIENT LES CONFIGURATIOND DE TOUS LES SERVICES A PARTAGER, IL SERA LANCER EN PREMIER POUR QUE LES AUTRES PUISSENT CHERCHER LEUR CONFIGURATION

project = banking-project
class = Master pro 2025-2026
semester = 2
prof = Mr. Dupont
student = Komol Daniel
heure = 16h par semaine